/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProfilePostRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  role?: string;
  isAuthor?: boolean;
}
