server:
  port: 8082
spring:
  application:
    name: user
  profiles:
    active: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:/db/master_changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres

